
spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=JavaTesting;trustServerCertificate=true;
    username: sa
    password: lenh0205
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect

server:
  port: 8081

